# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.srcs/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_bd_pidmc_1_0.xci
# IP: The module: 'pidmc_bd_pidmc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i0/pidmc_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i0 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i1/pidmc_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i1 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i2/pidmc_c_addsub_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i2 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i3/pidmc_c_addsub_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i3 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i4/pidmc_c_addsub_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i4 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i4} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i0/pidmc_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i0 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i1/pidmc_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i1 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i2/pidmc_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i2 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i3/pidmc_mult_gen_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i3 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i4/pidmc_mult_gen_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i4 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/constrs/pidmc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pidmc_bd_pidmc_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.srcs/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_bd_pidmc_1_0.xci
# IP: The module: 'pidmc_bd_pidmc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i0/pidmc_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i0 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i1/pidmc_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i1 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i2/pidmc_c_addsub_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i2 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i3/pidmc_c_addsub_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i3 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_c_addsub_v12_0_i4/pidmc_c_addsub_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_c_addsub_v12_0_i4 || ORIG_REF_NAME==pidmc_c_addsub_v12_0_i4} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i0/pidmc_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i0 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i1/pidmc_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i1 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i2/pidmc_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i2 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i3/pidmc_mult_gen_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i3 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_mult_gen_v12_0_i4/pidmc_mult_gen_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_mult_gen_v12_0_i4 || ORIG_REF_NAME==pidmc_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/constrs/pidmc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pidmc_bd_pidmc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
