# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/pidmc_clock.xdc

# XDC: imports/sysgen/pidmc.xdc

# Block Designs: bd/pidmc_bd/pidmc_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_bd || ORIG_REF_NAME==pidmc_bd} -quiet] -quiet

# IP: bd/pidmc_bd/ip/pidmc_bd_pidmc_1_0/pidmc_bd_pidmc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pidmc_bd_pidmc_1_0 || ORIG_REF_NAME==pidmc_bd_pidmc_1_0} -quiet] -quiet

# XDC: /xilinxworks/sysgen/pid_panda/netlist/ip/pidmc/src/ip_catalog/pidmc.gen/sources_1/bd/pidmc_bd/pidmc_bd_ooc.xdc
